// Définitions statiques partagées entre le glossaire et les tooltips.
// Le terme dynamique est la clé, la définition est la valeur.

export const DEFINITIONS: Record<string, string> = {
  // ── Statuts des dossiers ──
  'Adopté par l\'Assemblée nationale': 'L\'Assemblée nationale a voté le texte. Le Sénat doit encore se prononcer.',
  'Adopté par le Parlement': 'Les deux chambres ont voté le texte dans les mêmes termes. Il attend la promulgation par le Président.',
  'Adopté par le Sénat': 'Le Sénat a voté le texte. L\'Assemblée nationale doit encore se prononcer.',
  'En cours d\'examen': 'Le texte est encore en discussion au Parlement. Il n\'a pas encore été adopté définitivement.',
  'Promulguée': 'Le texte a été signé par le Président de la République et publié au Journal officiel. Il a force de loi.',
  'Rejeté': 'Le texte a été rejeté par l\'une des chambres ou les deux. Un nouveau dépôt reste possible.',

  // ── Types de procédures ──
  'Allocution du Président de l\'Assemblée nationale': 'Discours officiel prononcé par le président de l\'Assemblée nationale en séance. Ce n\'est pas un texte législatif.',
  'Commission d\'enquête': 'Enquête parlementaire sur un sujet d\'intérêt public, menée par un groupe de députés. Elle aboutit à un rapport, pas à une loi.',
  'Engagement de la responsabilité gouvernementale': 'Procédure par laquelle le Premier ministre engage la responsabilité du gouvernement devant l\'Assemblée (article 49 de la Constitution). Elle peut entraîner l\'adoption d\'un texte sans vote ou le renversement du gouvernement.',
  'Mission d\'information': 'Groupe de travail parlementaire chargé d\'étudier un sujet précis et de produire un rapport. Elle n\'a pas de pouvoir contraignant.',
  'Pétitions': 'Demande adressée par des citoyens au Parlement sur un sujet d\'intérêt général. Elle est examinée par une commission mais ne produit pas de loi.',
  'Projet de loi de financement de la sécurité sociale': 'Budget annuel de la Sécurité sociale, déposé par le gouvernement chaque automne. Il fixe les objectifs de dépenses et de recettes pour l\'année suivante.',
  'Projet de loi de finances de l\'année': 'Budget annuel de l\'État, déposé par le gouvernement chaque automne. Il autorise les dépenses et les recettes pour l\'année suivante.',
  'Projet de loi de finances rectificative': 'Modification du budget de l\'État en cours d\'année. Il corrige les prévisions initiales en fonction de la conjoncture.',
  'Projet de loi ordinaire': 'Texte préparé et déposé par le gouvernement, soumis ensuite au vote du Parlement. C\'est le type de texte législatif le plus courant.',
  'Projet de ratification des traités et conventions': 'Autorisation donnée par le Parlement pour que le Président ratifie un traité international. Le Parlement ne peut pas modifier le texte du traité.',
  'Projet ou proposition de loi constitutionnelle': 'Texte visant à modifier la Constitution. Son adoption nécessite une procédure spéciale (référendum ou vote du Congrès).',
  'Projet ou proposition de loi organique': 'Texte qui précise les modalités d\'application de la Constitution. Son adoption suit une procédure renforcée avec contrôle obligatoire du Conseil constitutionnel.',
  'Proposition de loi ordinaire': 'Texte déposé par un ou plusieurs parlementaires (député ou sénateur). Contrairement au projet de loi, il n\'émane pas du gouvernement.',
  'Rapport d\'information sans mission': 'Rapport produit par un ou plusieurs parlementaires sur un sujet de leur choix. Il informe le Parlement mais n\'a aucune valeur contraignante.',
  'Résolution': 'Texte exprimant une position du Parlement, sans valeur législative. Elle ne crée ni obligation ni droit.',
  'Résolution Article 34-1': 'Résolution adoptée sur le fondement de l\'article 34-1 de la Constitution, permettant au Parlement d\'exprimer un souhait ou une orientation. Elle n\'a pas de force de loi.',
  'Responsabilité pénale du président de la république': 'Procédure exceptionnelle prévue par la Constitution pour engager la responsabilité pénale du chef de l\'État. Elle passe par la Haute Cour.',

  // ── Étapes législatives ──
  '1er dépôt d\'une initiative.': 'Première étape : l\'auteur (gouvernement ou parlementaire) dépose officiellement son texte au Parlement. C\'est le point de départ de la procédure.',
  '1ère lecture (1ère assemblée saisie)': 'Premier examen complet du texte par la chambre qui l\'a reçu en premier. Elle comprend le travail en commission puis le débat en séance publique.',
  '1ère lecture (2ème assemblée saisie)': 'Premier examen du texte par la seconde chambre, après adoption par la première. La navette parlementaire commence.',
  'Accord international': 'Traité ou convention internationale associé au dossier. Le Parlement autorise sa ratification mais ne peut pas en modifier le contenu.',
  'Avis du Conseil d\'Etat': 'Avis consultatif rendu par le Conseil d\'État sur un projet de loi avant son dépôt au Parlement. Il est obligatoire pour les projets de loi.',
  'Commission Mixte Paritaire': 'Réunion de 7 députés et 7 sénateurs chargés de trouver un texte de compromis quand les deux chambres ne sont pas d\'accord. Son résultat est ensuite soumis au vote des deux assemblées.',
  'Conclusion du conseil constitutionnel': 'Décision finale du Conseil constitutionnel sur la conformité du texte à la Constitution. Elle peut valider, censurer partiellement ou totalement le texte.',
  'Conseil constitutionnel': 'Phase de contrôle de constitutionnalité du texte. Le Conseil vérifie que la loi respecte la Constitution.',
  'Convocation d\'une CMP': 'Le Premier ministre (ou les présidents des deux assemblées pour une proposition de loi) demande la réunion d\'une Commission Mixte Paritaire. C\'est le début de la procédure de conciliation.',
  'Création d\'une commission d\'enquête': 'Décision de l\'Assemblée nationale de lancer une enquête parlementaire. La commission dispose de pouvoirs d\'investigation étendus.',
  'Création d\'une mission d\'information': 'Décision de créer un groupe de travail parlementaire sur un sujet donné. La mission produira un rapport à l\'issue de ses travaux.',
  'Débat': 'Discussion en séance publique sur le texte ou un sujet lié. Les parlementaires exposent leurs positions et examinent les amendements.',
  'Décision': 'Vote final de la chambre sur le texte en séance publique. Le texte est adopté, rejeté, ou adopté avec modifications.',
  'Décision de la CMP': 'Résultat des travaux de la Commission Mixte Paritaire. Elle peut aboutir à un accord (texte commun) ou à un échec (désaccord).',
  'Décision sur une motion de censure': 'Vote de l\'Assemblée nationale sur une motion de censure contre le gouvernement. Si elle est adoptée, le gouvernement est renversé.',
  'Dépôt d\'un projet de loi': 'Le gouvernement dépose officiellement un texte au Parlement. Il est accompagné d\'une étude d\'impact et de l\'avis du Conseil d\'État.',
  'Dépôt d\'une déclaration du gouvernement': 'Le gouvernement soumet une déclaration officielle au Parlement, pouvant donner lieu à un débat. Elle n\'a pas de valeur législative.',
  'Dépôt d\'une initiative en navette': 'Transmission du texte d\'une chambre à l\'autre après un premier vote. La navette se poursuit jusqu\'à l\'adoption d\'un texte identique.',
  'Dépôt d\'une lettre rectificative.': 'Le gouvernement modifie son propre projet de loi avant ou pendant son examen. Cela permet d\'actualiser le texte sans le retirer.',
  'Dépôt de rapport': 'Le rapporteur dépose le rapport de la commission auprès de l\'assemblée. Ce document résume les travaux de la commission et ses recommandations.',
  'Dépôt du rapport d\'une CMP': 'Publication du texte de compromis élaboré par la Commission Mixte Paritaire. Il sera soumis au vote des deux chambres.',
  'deuxième lecture': 'Deuxième examen du texte par une chambre, après que l\'autre chambre l\'a modifié. Le débat porte uniquement sur les points de désaccord restants.',
  'Discussion en séance publique': 'Examen du texte par l\'ensemble des parlementaires dans l\'hémicycle. C\'est lors de cette phase que les amendements sont débattus et votés.',
  'Etude d\'impact': 'Document obligatoire accompagnant les projets de loi, évaluant les conséquences économiques, sociales et juridiques du texte. Il est publié avant le début de l\'examen.',
  'Le gouvernement déclare l\'urgence / engage la procédure accélérée': 'Le gouvernement demande un examen rapide du texte, limitant la navette à une seule lecture par chambre. Cela accélère considérablement le processus.',
  'Lecture définitive': 'Dernier vote de l\'Assemblée nationale quand la CMP a échoué et que le gouvernement lui donne le dernier mot. Le Sénat ne peut plus s\'y opposer.',
  'Lecture unique': 'Le texte est examiné en une seule lecture par une chambre, sans possibilité de navette. C\'est le cas pour certaines résolutions ou textes spéciaux.',
  'Mise en application de la loi': 'Publication des décrets et arrêtés nécessaires pour que la loi entre concrètement en vigueur. Sans ces textes, certaines dispositions restent inapplicables.',
  'Motion de censure': 'Procédure par laquelle l\'Assemblée nationale peut renverser le gouvernement. Elle nécessite la signature d\'au moins un dixième des députés pour être déposée.',
  'Motion de procédure': 'Demande formulée en séance pour modifier le déroulement de l\'examen d\'un texte. Elle peut viser à rejeter le texte sans débat ou à le renvoyer en commission.',
  'Nomination de rapporteur': 'La commission désigne un de ses membres pour étudier le texte en détail et rédiger un rapport. Le rapporteur devient le référent du texte en commission et en séance.',
  'Nomination de rapporteur budgétaire': 'La commission désigne un rapporteur spécialisé pour examiner une partie du budget. Chaque rapporteur budgétaire suit un domaine précis (défense, éducation, santé, etc.).',
  'Nouvelle Lecture': 'Reprise de l\'examen du texte par une chambre après l\'échec de la Commission Mixte Paritaire. Les deux chambres tentent de se mettre d\'accord sur un texte commun.',
  'Promulgation d\'une loi': 'Le Président de la République signe la loi et ordonne sa publication au Journal officiel. La loi entre en vigueur le lendemain de sa publication, sauf disposition contraire.',
  'Promulgation de la loi': 'Le Président de la République signe la loi et ordonne sa publication au Journal officiel. La loi entre en vigueur le lendemain de sa publication, sauf disposition contraire.',
  'Rapport sur l\'application des lois': 'Bilan établi par le Parlement sur la mise en œuvre effective d\'une loi votée. Il vérifie si les décrets d\'application ont été publiés.',
  'Renvoi en commission au fond': 'Le texte est transmis à la commission principale chargée de l\'examiner. C\'est elle qui rédigera le rapport et proposera des amendements.',
  'Renvoi préalable': 'Procédure par laquelle le texte est renvoyé en commission avant d\'être débattu en séance. Cela permet un examen approfondi avant le débat public.',
  'Renvoi préalable à la CAE': 'Le texte est renvoyé à la Commission des affaires étrangères pour examen. C\'est le cas notamment pour les traités et conventions internationales.',
  'Retrait d\'une initiative': 'L\'auteur du texte (gouvernement ou parlementaire) retire son propre projet ou proposition. Le dossier est clos.',
  'Réunion de commission': 'Séance de travail de la commission parlementaire chargée d\'examiner le texte. Les amendements y sont discutés et votés avant le passage en séance publique.',
  'Saisine du conseil constitutionnel': 'Des parlementaires, le Président ou le Premier ministre demandent au Conseil constitutionnel de vérifier la conformité du texte à la Constitution. Cette étape peut intervenir avant la promulgation.',
  'Saisine pour avis d\'une commission': 'Une commission est consultée pour donner son avis sur un texte qui relève principalement d\'une autre commission. Son avis est consultatif.',
  'Travaux': 'Ensemble des activités liées à l\'examen d\'un dossier. Ce terme générique regroupe les réunions, auditions et discussions.',
  'Travaux d\'une commission saisie pour avis': 'Travaux menés par une commission consultée pour avis sur un texte. Elle peut proposer des amendements mais la décision finale revient à la commission au fond.',
  'Travaux de la commission saisie au fond': 'Travaux de la commission principale chargée d\'examiner le texte. C\'est elle qui rédige le rapport et les amendements soumis à l\'ensemble de l\'assemblée.',
  'Travaux des commissions': 'Phase d\'examen du texte par les commissions parlementaires. Les commissaires auditionnent des experts, débattent et proposent des modifications.',

  // ── Provenance des textes ──
  'Texte Déposé': 'Version initiale du texte, telle que déposée par son auteur (parlementaire ou gouvernement). C\'est le point de départ de la procédure.',
  'Commission': 'Version du texte modifiée par la commission parlementaire chargée de l\'examiner. Elle intègre les amendements adoptés en commission.',
  'Séance': 'Version du texte adoptée en séance publique, après débats et amendements dans l\'hémicycle. C\'est le texte tel que voté par la chambre.',
  'LEGIFRANCE': 'Version officielle publiée au Journal officiel après promulgation. C\'est le texte de loi définitif, tel que référencé sur Légifrance.',
}
